### ISSUE TITLE
ounce:project generates ppf files in project folder but lists them in the root of the project inside the paf file

### ISSUE THREAD

**Issue by kjweinert** [AppSecDev/ounce-maven-plugin#11]
When running mvn ounce:project ounce:application the ppf files get generated in the project folder but points to the root of the application in the paf file.

ppf file gets generated here:
.\project1\project1.ppf

The paf file:
`<Project ltd_name="java" path=".\project1.ppf"/>`

**Comment by bjvijayakumar** [comment]
The reported issue has been addressed now.
