### ISSUE TITLE
Any directory provided to ounce.projectDir property must exist ahead of time.

### ISSUE THREAD

**Issue by blindenvy** [AppSecDev/ounce-maven-plugin#3]
The `project-only` goal has a parameter projectDir which is the directory where the ppf file will be written to. If that directory doesn't exist the plugin will fail. It is common practice to put content that is produced by maven builds under ${project.build.directory} and to keep that content organized. For instance a reasonable value to specify for projectDir is `${project.build.directory}/appscan`. The plugin should check for existence of the path and create it if it doesn't exist.

**Comment by mattmurp** [comment]
This is fixed with the updates for scanning precompiled classes.
